project/fresh/urls.py
from django.urls import path
from . import views
from .views import delete_product, delete_product1, delete_product2

urlpatterns = [
    path('', views.news_home, name='fresh_home'),
    path('create', views.create, name='create'),
    path('<int:pk>', views.NewsDetailview.as_view(), name='fresh-detail'),
    path('login', views.LoginView.as_view(), name='login_page'),
    path('register', views.RegisterUserView.as_view(), name='register_page'),
    path('logout', views.LogoutView.as_view(), name='logout_page'),
    path('category/<int:category_id>/', views.category_detail, name='category_detail'),
    path('delete/<int:product_id>/', delete_product, name='delete_product'),
    path('moroz/<int:category_id>/', views.category_detail1, name='moroz'),
    path('moroz/delete/<int:product_id>/', delete_product1, name='delete_product1'),
    path('cupboard/<int:category_id>/', views.category_detail2, name='cupboard'),
    path('cupboard/delete/<int:product_id>/', delete_product2, name='delete_product2'),
]

project/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.main, name='home'),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),
    path('product', views.product, name='product'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('main.urls')),
                  path('fresh/', include('fresh.urls'))
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/fresh/models.py
from django.db import models
from django.utils import timezone
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=64, verbose_name='название')

    def __str__(self):
        return self.name

class Articles(models.Model):
    title = models.CharField('Название', max_length=100, default='', blank=False)
    date = models.DateField('Дата изготовления')
    date1 = models.DateField('Дата истечения срока годности')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='категория')
    photo = models.ImageField(upload_to='images/', verbose_name='Фото', blank=True, null=True)
    current_date = models.DateField('Текущая дата', editable=False, null=True, blank=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        # Обновляем поле current_date при каждом сохранении объекта
        self.current_date = timezone.now().date()
        super().save(*args, **kwargs)

    def clean(self):
        # Вызываем clean родительского класса для проверки полей модели
        super().clean()

        # Проверяем, что date не больше date1
        if self.date and self.date1 and self.date > self.date1:
            raise ValidationError({'date': 'Дата изготовления не может быть больше даты истечения срока годности'})

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

project/fresh/forms.py
from django.contrib.auth.models import User
from django.forms import ModelForm, TextInput, DateInput, Select, ClearableFileInput
from .models import Articles
from django.contrib.auth.forms import AuthenticationForm
from django import forms
from datetime import datetime



class ArticlesForm(forms.ModelForm):
    class Meta:
        model = Articles
        fields = ['title', 'date1', 'date', 'category', 'photo']

        widgets = {
            "title": forms.TextInput(attrs={'class': 'form-control'}),
            "date": forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            "date1": forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            "category": forms.Select(attrs={'class': 'form-control'}),
        }

    def clean(self):
        cleaned_data = super().clean()
        date = cleaned_data.get('date')
        date1 = cleaned_data.get('date1')

        if date and date1:
            # Преобразование строковых значений дат в объекты datetime
            date = datetime.strptime(str(date), '%Y-%m-%d').date()
            date1 = datetime.strptime(str(date1), '%Y-%m-%d').date()

            if date > date1:
                self.add_error('date', 'Дата изготовления не может быть больше даты истечения срока годности')
                self.add_error('date1', 'Дата изготовления не может быть больше даты истечения срока годности')

    def clean(self):
        cleaned_data = super().clean()
        date = cleaned_data.get('date')
        date1 = cleaned_data.get('date1')

        if date and date1 and date > date1:
            self.add_error('date', 'Дата изготовления не может быть больше даты истечения срока годности')
            self.add_error('date1', 'Дата изготовления не может быть больше даты истечения срока годности')
class AuthUserForm(AuthenticationForm, forms.ModelForm):
    class Meta:
        model = User
        fields = ('username','password')
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'


class RegisterUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

project/fresh/views.py
from django.contrib.auth import authenticate, login
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from .models import Articles, Category
from .forms import ArticlesForm, AuthUserForm, RegisterUserForm
from django.views.generic import DetailView, CreateView
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.models import User
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from datetime import datetime
from django.shortcuts import render, redirect
from .forms import ArticlesForm
from django.contrib import messages


# Create your views here.
def news_home(request):
    fresh = Articles.objects.all()
    return render(request, 'main/product.html', {'fresh': fresh});


class NewsDetailview(DetailView):
    model = Articles
    template_name = 'fresh/create.html'
    context_object_name = 'article'


def create(request):
    if request.method == 'POST':
        form = ArticlesForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Продукт успешно добавлен!')
            return redirect('create')
        else:
            messages.error(request, 'Форма была неверной')

    form = ArticlesForm()
    return render(request, 'fresh/create.html', {'form': form})


class LoginView(LoginView):
    template_name = 'fresh/login.html'
    form_class = AuthUserForm
    success_url = reverse_lazy('home')

    def get_success_url(self):
        return self.success_url


class RegisterUserView(CreateView):
    model = User
    template_name = 'fresh/register_page.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('home')
    success_msg = 'Пользователь успешно создан'

    def form_valid(self, form):
        form_valid = super().form_valid(form)
        username = form.cleaned_data["username"]
        password = form.cleaned_data["password"]
        aut_user = authenticate(username=username, password=password)
        login(self.request, aut_user)
        return form_valid


class Logout(LogoutView):
    next_page = reverse_lazy('home')


def category_detail(request, category_id):
    category = get_object_or_404(Category, pk=category_id)
    products = category.articles_set.filter(category_id=1).order_by('date1')  # Сортировка по убыванию даты
    now = datetime.now().date()  # Текущая дата

    products_with_days = []
    for product in products:
        days_until_expiration = (product.date1 - now).days
        products_with_days.append({'product': product, 'days_until_expiration': days_until_expiration})

    return render(request, 'fresh/category_detail.html', {'category': category, 'products_with_days': products_with_days, 'now': now})

def delete_product(request, product_id):
    product = get_object_or_404(Articles, id=product_id)
    product.delete()
    return redirect('category_detail', category_id=1)


def category_detail1(request, category_id):
    category = get_object_or_404(Category, pk=category_id)
    products = category.articles_set.filter(category_id=2).order_by('date1')  # Сортировка по убыванию даты
    now = datetime.now().date()  # Текущая дата

    products_with_days = []
    for product in products:
        days_until_expiration = (product.date1 - now).days
        products_with_days.append({'product': product, 'days_until_expiration': days_until_expiration})

    return render(request, 'fresh/moroz.html', {'category': category, 'products_with_days': products_with_days, 'now': now})

def delete_product1(request, product_id):
    product = get_object_or_404(Articles, id=product_id)
    product.delete()
    return redirect('moroz', category_id=2)

def category_detail2(request, category_id):
    category = get_object_or_404(Category, pk=category_id)
    products = category.articles_set.filter(category_id=3).order_by('date1')  # Сортировка по убыванию даты
    now = datetime.now().date()  # Текущая дата

    products_with_days = []
    for product in products:
        days_until_expiration = (product.date1 - now).days
        products_with_days.append({'product': product, 'days_until_expiration': days_until_expiration})

    return render(request, 'fresh/cupboard.html', {'category': category, 'products_with_days': products_with_days, 'now': now})

def delete_product2(request, product_id):
    product = get_object_or_404(Articles, id=product_id)
    category_id = product.category_id  # Получаем ID категории из продукта
    product.delete()
    return redirect(reverse('cupboard', kwargs={'category_id': category_id}))

project/fresh/templates/fresh/category_detail.html
{% extends 'main/layout.html' %}
{% load static %}

{% block title %}{{ category.name }}{% endblock %}

{% block header %}
    <!-- Ваши теги заголовка, если они есть -->
{% endblock %}

{% block content %}
   <style>


    h1 {
        text-align: center;
        color: #39559D;
    }

    .product-container {
        border-radius: 8px;
        margin-bottom: 20px;
        margin-left: 300px;
        background-color: white;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        transition: box-shadow 0.3s ease-in-out;
    }

    .product-container:hover {
        box-shadow: 0 8px 12px rgba(0, 0, 0, 0.2);
    }

    .delete-button {
        background-color: #4CAF50;
        color: white;
        padding: 8px 16px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        transition: background-color 0.3s;
         margin-left: -110px;
    }

    .delete-button.expired {
        background-color: #D32F2F;
    }

    .delete-button:hover {
        background-color: #FF5252;
    }

    .store_img {
        position: absolute;
        top: 10%;
        right: 1%;
        width: 25%;
    }
    aside {

    float: left;
    background: #1E3C40;
    width: 20%;
    /*padding: 2.5%;*/
    height: 300vh;
    position: fixed;
    color: #000;
    }

</style>
  <h1 style="text-align: center; color: #39559D;">{{ category.name }}</h1>
{% for product_info in products_with_days %}
  {% if product_info.product.category_id == 1 %}
    <div style="margin-bottom: 20px;">
        <div class="product-container" style="border: 2px solid {% if product_info.product.date1 < now %}red{% else %}green{% endif %}; padding: 10px;">
            <h2>{{ product_info.product.title }}</h2>
            <p>Дата изготовления: {{ product_info.product.date }}</p>
            <p>Дата истечения: {{ product_info.product.date1 }}</p>
            {% if product_info.product.date1 < now %}
                <p style="color: red;">Срок годности истек</p>
            {% else %}
                <p>Осталось дней: {{ product_info.days_until_expiration }}</p>
            {% endif %}
            {% if product_info.product.photo %}
                <img src="{{ product_info.product.photo.url }}" alt="{{ product_info.product.title }}">
            {% endif %}
            <!-- Кнопка удаления продукта -->
            <form method="post" action="{% url 'delete_product' product_info.product.id %}">
                {% csrf_token %}
                <button type="submit" class="delete-button {% if product_info.product.date1 < now %}expired{% endif %}">
                    Удалить продукт
                </button>
            </form>
        </div>
    </div>
  {% endif %}
{% endfor %}




<div class="features" style="margin: 0;">
    <img class="store_img" src="{% static 'main/img/1.png' %}">
</div>
{% endblock %}

project/fresh/templates/fresh/create.html
{% extends 'main/layout.html' %}
{% load static %}
{% block title %}Форма добавления{% endblock %}
{% block content %}
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css">
    <script src="https://cdn.jsdelivr.net/npm/toastify-js"></script>
</head>
<div class="features">
    <h1 style="margin-left:-100px; font-size: 5rem; color: #39559D;">Добавление продукта</h1>
    <form method="post">

        {% csrf_token %}
        Название продукта {{ form.title }}<br>
        Дата производства
        <div class="form-group">
            <input type="date" name="date" id="id_date" class="form-control" value="{{ form.date.value }}" min="2021-01-01">
        </div>
        Дата окончания срока годности
        <div class="form-group">
            <input type="date" name="date1" id="id_date1" class="form-control" value="{{ form.date1.value }}" min="" max="">
        </div>
        Место хранения {{ form.category }}<br>

        <span>{{ error }}</span>
        <button class="btn "
                style="background-color:#A5D6A7; transform: scale(1.5); margin-top:40px; margin-left:110px; width:240px;"
                type="submit">ДОБАВИТЬ
        </button>
    </form>
    {% if messages %}
        {% for message in messages %}
            <script>
                Toastify({
                    text: "{{ message }}",
                    backgroundColor: "linear-gradient(to right, #00b09b, #96c93d)",
                    duration: 2000,
                }).showToast();
            </script>
        {% endfor %}
    {% endif %}
</div>

<script>
    // Получаем элемент даты производства
    var dateInput = document.getElementById('id_date');
    // Получаем элемент даты окончания срока годности
    var date1Input = document.getElementById('id_date1');

    // Устанавливаем обработчик изменения значения
    dateInput.addEventListener('change', function () {
        // Получаем выбранную дату
        var selectedDate = new Date(dateInput.value);

        // Устанавливаем максимальную дату для date (текущая дата)
        var currentDate = new Date();
        dateInput.setAttribute('max', currentDate.toISOString().split('T')[0]);

        // Устанавливаем минимальную и максимальную даты для date1 (от выбранной даты до 3 лет вперед)
        var minDate1 = new Date(selectedDate);
        var maxDate1 = new Date(selectedDate);
        maxDate1.setFullYear(maxDate1.getFullYear() + 3);

        date1Input.setAttribute('min', selectedDate.toISOString().split('T')[0]);
        date1Input.setAttribute('max', maxDate1.toISOString().split('T')[0]);

        // Устанавливаем начальное значение для date1Input, если оно не было установлено
        if (!date1Input.value) {
            date1Input.value = selectedDate.toISOString().split('T')[0];
        }
    });
</script>
{% endblock %}

project/fresh/templates/fresh/cupboard.html
{% extends 'main/layout.html' %}
{% load static %}

{% block title %}{{ category.name }}{% endblock %}

{% block header %}
    <!-- Ваши теги заголовка, если они есть -->
{% endblock %}

{% block content %}
   <style>


    h1 {
        text-align: center;
        color: #39559D;

    }

    .product-container {
        border-radius: 8px;
        margin-bottom: 20px;
        margin-left: 300px;
        background-color: white;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        transition: box-shadow 0.3s ease-in-out;
    }

    .product-container:hover {
        box-shadow: 0 8px 12px rgba(0, 0, 0, 0.2);
    }


    .delete-button {
        background-color: #4CAF50;
        color: white;
        padding: 8px 16px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        transition: background-color 0.3s;
        margin-left: -110px;
    }

    .delete-button.expired {
        background-color: #D32F2F;
    }

    .delete-button:hover {
        background-color: #FF5252;
    }

    .store_img {
        position: absolute;
        top: 11%;
        right: 1%;
        width: 20%;
    }
    aside {

    float: left;
    background: #1E3C40;
    width: 20%;
    /*padding: 2.5%;*/
    height: 250vh;
    color: #000;
     position: fixed;
}
</style>
  <h1 style="text-align: center; color: #39559D;top: 100cm;">{{ category.name }}</h1>
{% for product_info in products_with_days %}
  {% if product_info.product.category_id == 3 %}
    <div style="margin-bottom: 20px;">
        <div class="product-container" style="border: 2px solid {% if product_info.product.date1 < now %}red{% else %}green{% endif %}; padding: 10px;">
            <h2>{{ product_info.product.title }}</h2>
            <p>Дата изготовления: {{ product_info.product.date }}</p>
            <p>Дата истечения: {{ product_info.product.date1 }}</p>
            {% if product_info.product.date1 < now %}
                <p style="color: red;">Срок годности истек</p>
            {% else %}
                <p>Осталось дней: {{ product_info.days_until_expiration }}</p>
            {% endif %}
            {% if product_info.product.photo %}
                <img src="{{ product_info.product.photo.url }}" alt="{{ product_info.product.title }}">
            {% endif %}
            <!-- Кнопка удаления продукта -->
            <form method="post" action="{% url 'delete_product2' product_info.product.id %}">
                {% csrf_token %}
                <button type="submit" class="delete-button {% if product_info.product.date1 < now %}expired{% endif %}">
                    Удалить продукт
                </button>
            </form>
        </div>
    </div>
  {% endif %}
{% endfor %}




<div class="features" style="margin: 0;">
    <img class="store_img" src="{% static 'main/img/3.png' %}">
</div>
{% endblock %}

project/fresh/templates/fresh/details_view.html
{% extends 'main/layout.html' %}

{% block title %}{{ article.title }}{% endblock %}

{% block content %}
<div class="features">
    <h1>{{ article.title }}</h1>
    <p>Изготовлен: {{ article.date }}</p>
    <p>Годен до: {{ article.date1 }}</p>
    <p>Категория: {{ article.category }}</p>
    <p>{{ article.photo }}</p>
    {% if article.photo %}
    <div class="picture">
        <img src="{{ article.photo.url }}">
    </div>


    {% else %}
    <p>Изображения нет</p>
    {% endif %}
</div>
{% endblock %}

project/fresh/templates/fresh/fresh_home.html
{% extends 'main/layout.html' %}

{% block title %}Продукты{% endblock %}

{% block content %}
<div class="features">
    <h1 style="color: #139B18; font-size: 4rem; padding-right:60px;">Продукты</h1>
    {% for el in fresh %}
    <div class="alert alert-warning" style="background-color:#E6F5BA;">
        <h3><a href="{% url 'fresh-detail' el.id %}">{{ el.title }}</a></h3>
        {% if el.category %} <!-- Проверка наличия категории у продукта -->
            Категория: {{ el.category.name }}<br> <!-- Показываем название категории -->
        {% endif %}
        Изготовлен: {{ el.date }}<br>
        Годен до: {{ el.date1 }}
        <!-- Другие детали продукта, которые вы хотите показать -->
    </div>
    {% empty %}
    <p>Нет доступных продуктов.</p>
    {% endfor %}
</div>
{% endblock %}

project/fresh/templates/fresh/login.html
{% extends 'main/layout.html' %}

{% block content %}
<h1 class="login">Авторизация</h1>
<div class="col-4">
    <form id="add_form" class="login_form" method="post">
        {% csrf_token %}
        {{form}}
        <button form="add_form" type="submit" class="btn  mt-4" style="background-color:#A5D6A7; margin-left:130px; width:140px;">ВОЙТИ</button>
        <p><a href="{% url 'home' %}" style="color:#000; margin-left:140px;" >Вернуться назад</a></p>
    </form>
</div>
<style>
.login_form input{

color: #B2DFB6;
border:1px solid #B2DFB6;
}

.login_form label{
margin-top:15px;
}
</style>
{% endblock %}

project/fresh/templates/fresh/moroz.html
{% extends 'main/layout.html' %}
{% load static %}

{% block title %}{{ category.name }}{% endblock %}

{% block header %}
    <!-- Ваши теги заголовка, если они есть -->
{% endblock %}

{% block content %}
   <style>


    h1 {
        text-align: center;
        color: #39559D;
    }

     .product-container {
        border-radius: 8px;
        margin-bottom: 20px;
        margin-left: 300px;
        background-color: white;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        transition: box-shadow 0.3s ease-in-out;
    }

    .product-container:hover {
        box-shadow: 0 8px 12px rgba(0, 0, 0, 0.2);
    }

    .delete-button {
        background-color: #4CAF50;
        color: white;
        padding: 8px 16px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        transition: background-color 0.3s;
         margin-left: -110px;
    }

    .delete-button.expired {
        background-color: #D32F2F;
    }

    .delete-button:hover {
        background-color: #FF5252;
    }

    .store_img {
        position: absolute;
        top: 12%;
        right: 1%;
        width: 20%;
    }
    aside {

    float: left;
    background: #1E3C40;
    width: 20%;
    /*padding: 2.5%;*/
    height: 250vh;
    color: #000;
    position: fixed;

}
</style>
  <h1 style="text-align: center; color: #39559D;">{{ category.name }}</h1>
{% for product_info in products_with_days %}
  {% if product_info.product.category_id == 2 %}
    <div style="margin-bottom: 20px;">
        <div class="product-container" style="border: 2px solid {% if product_info.product.date1 < now %}red{% else %}green{% endif %}; padding: 10px;">
            <h2>{{ product_info.product.title }}</h2>
            <p>Дата изготовления: {{ product_info.product.date }}</p>
            <p>Дата истечения: {{ product_info.product.date1 }}</p>
            {% if product_info.product.date1 < now %}
                <p style="color: red;">Срок годности истек</p>
            {% else %}
                <p>Осталось дней: {{ product_info.days_until_expiration }}</p>
            {% endif %}
            {% if product_info.product.photo %}
                <img src="{{ product_info.product.photo.url }}" alt="{{ product_info.product.title }}">
            {% endif %}
            <!-- Кнопка удаления продукта -->
            <form method="post" action="{% url 'delete_product1' product_info.product.id %}">
                {% csrf_token %}
                <button type="submit" class="delete-button {% if product_info.product.date1 < now %}expired{% endif %}">
                    Удалить продукт
                </button>
            </form>
        </div>
    </div>
  {% endif %}
{% endfor %}




<div class="features" style="margin: 0;">
    <img class="store_img" src="{% static 'main/img/2.png' %}">
</div>
{% endblock %}

project/fresh/templates/fresh/register_page.html
{% extends 'main/layout.html' %}

{% block content %}
    <h1 class="registration-title" style="margin-left: 60px;">Регистрация</h1>
    <div class="col-4">
        <form id="add_form" class="login_form" method="post">
            {% csrf_token %}
            {{form}}
            <button form="add_form" type="submit" class="btn  mt-4" style="background-color:#A5D6A7; margin-left:110px; width:180px;">ЗАРЕГИСТРИРОВАТЬ</button>
            <p><a href="{% url 'home' %}" style="color:#000; margin-left:140px;">Вернуться назад</a></p>
        </form>
    </div>
{% endblock %}